AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Enviornment for the "lab"

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'

Outputs:
  S3Bucket:
    Description: S3 bucket name
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-S3Bucket"